#ifndef H_CONSTANTES
#define H_CONSTANTES 0


#define HAUTEUR 800
#define LARGEUR 600
#define BPP 32
#define ECART_ICONE 64 
#define CENTRAGE_LOGO_X 175
#define CENTRAGE_LOGO_Y 400
#define CENTRAGE_ECRAN_X 175
#define CENTRAGE_ECRAN_Y 100
#define L 10
#define XL 12
#define XXL 14
#define BLOC 32
#define DEPART_BLOC_X 210
#define DEPART_BLOC_Y 50
#define CENTRAGE_LOGO_X_MUSIQUE 730
#define CENTRAGE_LOGO_Y_MUSIQUE 10
#define CENTRE_X 300
#define CENTRE_Y 400
#define SURFACE_BASE_Y 100                 
#define SURFACE_EVOLUE_Y 200
#define SURFACE_ULTIME_Y 300
#define LARGEUR_TEXTE 75
#define LONGUEUR_TEXTE 300
#define CHOIX_L_BASE_X 315
#define CHOIX_L_BASE_Y 120
#define CHOIX_XL_BASE_X 370
#define CHOIX_XL_BASE_Y 120
#define CHOIX_XXL_BASE_X 470
#define CHOIX_XXL_BASE_Y 120
#define CHOIX_L_EVOLUE_X 320
#define CHOIX_L_EVOLUE_Y 220
#define CHOIX_XL_EVOLUE_X 370
#define CHOIX_XL_EVOLUE_Y 220
#define CHOIX_XXL_EVOLUE_X 470
#define CHOIX_XXL_EVOLUE_Y 220
#define CHOIX_L_ULTIME_X 300
#define CHOIX_L_ULTIME_Y 320
#define CHOIX_XL_ULTIME_X 350
#define CHOIX_XL_ULTIME_Y 320
#define CHOIX_XXL_ULTIME_X 450
#define CHOIX_XXL_ULTIME_Y 320
#define LONGUEUR_L_X 50
#define LARGEUR_L_Y 60
#define LONGUEUR_XL_X 90
#define LARGEUR_XL_Y 70
#define LONGUEUR_XXL_X 125
#define LARGEUR_XXL_Y 70

#define CENTRAGE_JEU_L_X 224
#define CENTRAGE_JEU_L_Y 32
#define CENTRAGE_JEU_XL_X 192
#define CENTRAGE_JEU_XL_Y 32
#define CENTRAGE_JEU_XXL_X 192
#define CENTRAGE_JEU_XXL_Y 32

#define LARGEUR_JEU_L 320
#define LONGEUR_JEU_L 320
#define LARGEUR_JEU_XL 384
#define LONGEUR_JEU_XL 384
#define LARGEUR_JEU_XXL 448
#define LONGEUR_JEU_XXL 448
#define ICONE_SAVE_X 730
#define ICONE_SAVE_Y 65
#define ICONE_LOAD_X 730
#define ICONE_LOAD_Y 120
#define MOTION_X 256
#define MOTION_Y 64
#define CENTRAGE_LOGO_X_PREVIOUS 666
#define CENTRAGE_LOGO_Y_PREVIOUS 10
#define POSSIBILITES 2
#define UN 1
#define ZERO 0
#define CASEVIDE -1
#define NL printf("\n"); 

#define ICONE_HOME_X 666
#define ICONE_HOME_Y 65

#define ICONE_EXIT_X 666
#define ICONE_EXIT_Y 120

#define MESSAGE_ERREUR_BASE_X 570
#define MESSAGE_ERREUR_BASE_Y 184

#define MESSAGE_COMPTEUR_TOTAL_X 400
#define MESSAGE_COMPTEUR_TOTAL_Y 500

#define MESSAGE_COMPTEUR_ERREUR_X 0
#define MESSAGE_COMPTEUR_ERREUR_Y 500

#define MESSAGE_NIVEAU_BASE_X 50 
#define MESSAGE_NIVEAU_BASE_Y 100

#define MESSAGE_NIVEAU_EVOLUEE_X 50
#define MESSAGE_NIVEAU_EVOLUEE_Y 200

#define MESSAGE_NIVEAU_ULTIME_X 50
#define MESSAGE_NIVEAU_ULTIME_Y 300

#define MESSAGE_NIVEAU_DE_JEU_X CENTRE_X-ECART_ICONE
#define MESSAGE_NIVEAU_DE_JEU_Y 0

#endif



